### ISSUE TITLE
nginx and certbot issue

### ISSUE THREAD

**Issue by VincentBlackhorse** [mikehdt/aws-foundry-ssl#2]
There were zero rollbacks during the  stack deployment; however, Im only able to access the server via Public IPv4 address :30000.

I only redeployed the stack 4 times with various versions of V11 including the first stable and latest; however the issue is the same.

sudo cat /tmp/foundry-setup.log | less

```
++ sudo systemctl enable --now nginx
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /usr/lib/systemd/system/nginx.service.
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.
++ sudo sed -i 's/"hostname":.*/"hostname": "foundry\.*****.com",/g' /foundrydata/Config/options.json
++ sudo sed -i 's/"proxyPort":.*/"proxyPort": "80",/g' /foundrydata/Config/options.json
++ [[ False == \T\r\u\e ]]
++ systemctl restart nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.

```
In Cloud Watch Log group letsencrypt log stream: I see the error 

```
2023-11-05 00:46:34,519:ERROR:certbot.util:Error while running nginx -c /etc/nginx/nginx.conf -t.
nginx: [emerg] no host in ":80" of the "listen" directive in /etc/nginx/conf.d/foundryvtt.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed
2023-11-05 00:46:34,519:DEBUG:certbot._internal.plugins.disco:Misconfigured PluginEntryPoint#nginx: Error while running nginx -c /etc/nginx/nginx.conf -t.
nginx: [emerg] no host in ":80" of the "listen" directive in /etc/nginx/conf.d/foundryvtt.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed
Traceback (most recent call last):  
File "/opt/certbot/lib64/python3.9/site-packages/certbot_nginx/_internal/configurator.py", line 1014, in config_test 
util.run_script([self.conf('ctl'), "-c", self.nginx_conf, "-t"])  
File "/opt/certbot/lib64/python3.9/site-packages/certbot/util.py", line 199, in run_script    
raise errors.SubprocessError(msg)
certbot.errors.SubprocessError: Error while running nginx -c /etc/nginx/nginx.conf -t.
nginx: [emerg] no host in ":80" of the "listen" directive in /etc/nginx/conf.d/foundryvtt.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  
File "/opt/certbot/lib64/python3.9/site-packages/certbot/_internal/plugins/disco.py", line 112, in prepare    self._initialized.prepare()  
File "/opt/certbot/lib64/python3.9/site-packages/certbot_nginx/_internal/configurator.py", line 210, in prepare    self.config_test()  
File "/opt/certbot/lib64/python3.9/site-packages/certbot_nginx/_internal/configurator.py", line 1016, in config_test    
raise errors.MisconfigurationError(str(err))
certbot.errors.MisconfigurationError: Error while running nginx -c /etc/nginx/nginx.conf -t.
nginx: [emerg] no host in ":80" of the "listen" directive in /etc/nginx/conf.d/foundryvtt.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed
2023-11-05 00:46:34,520:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin
Interfaces: Authenticator, Installer, Plugin
Entry point: EntryPoint(name='nginx', value='certbot_nginx._internal.configurator:NginxConfigurator', group='certbot.plugins')
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at 0xffffa530d040>
Prep: Error while running nginx -c /etc/nginx/nginx.conf -t.
nginx: [emerg] no host in ":80" of the "listen" directive in /etc/nginx/conf.d/foundryvtt.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed

```
any help or suggestion appreciated! 

Thanks

**Comment by VincentBlackhorse** [comment]
ok figured it out. In the  setup file: foundryvtt.conf

`        listen                          :80;`

it doesnt recognize : before the 80.

**Comment by mikehdt** [comment]
Aha! I've been travelling and when I had a few moments I was playing around with what's needed to enable IPv6 for the server. Mainly due to AWS deciding to (and fair enough) start charging for reserved IPv4 addresses, so I'd at least like the option to free an IPv4.

I was reading an article and just put some stuff in based on that, but I didn't have the access / setup at the time to test it. I'm also not really bothering with branching because this is as much a learning project about AWS infra for myself as anything 😅

Will fix when I have a bit more time to poke around. Thanks!

**Comment by mikehdt** [comment]
This should be fixed now.
